#!/usr/bin/env bash
# 8sync palette cycler — switches Hyprland borders + kitty accent through
# a fixed set of neon dev palettes. Persistent across reloads.
#
# Bindings (set in 8sync-end4-bridge.conf):
#   Ctrl+Super+Shift+Right  → next palette
#   Ctrl+Super+Shift+Left   → previous palette
#   Ctrl+Super+Shift+P      → notify current
#
# State file: ~/.config/hypr/.8sync-palette-index
# Output file: ~/.config/hypr/8sync-palette.conf (sourced by glass theme)

set -e

STATE="$HOME/.config/hypr/.8sync-palette-index"
OUT="$HOME/.config/hypr/8sync-palette.conf"

# name | active_border_a | active_border_b | inactive_border | kitty_fg | kitty_accent_cur
PALETTES=(
  "cyber-cyan    | rgba(00FFFFee) | rgba(FF00FFee) | rgba(33445566) | #E8FFFF | #00FFFF"
  "tokyo-neon    | rgba(7AA2F7ee) | rgba(BB9AF7ee) | rgba(2A3050AA) | #C0CAF5 | #7AA2F7"
  "synthwave     | rgba(FF6AC1ee) | rgba(B084EBee) | rgba(2D1B4DAA) | #FFEAFA | #FF6AC1"
  "matrix-green  | rgba(00FF88ee) | rgba(00CCFFee) | rgba(0A2A1AAA) | #C8FFD8 | #00FF88"
  "lava-orange   | rgba(FF8C00ee) | rgba(FF1493ee) | rgba(3A1A0AAA) | #FFE0C0 | #FF8C00"
  "ice-violet    | rgba(88DDFFee) | rgba(7B5CFFee) | rgba(1A2A4AAA) | #DCEEFF | #88DDFF"
)

idx=$(cat "$STATE" 2>/dev/null || echo 0)
case "${1:-show}" in
  next) idx=$(( (idx + 1) % ${#PALETTES[@]} )) ;;
  prev) idx=$(( (idx - 1 + ${#PALETTES[@]}) % ${#PALETTES[@]} )) ;;
  set)  idx=$(( ${2:-0} % ${#PALETTES[@]} )) ;;
  show) : ;;
  *) echo "usage: $0 [next|prev|set <n>|show]"; exit 1 ;;
esac
echo "$idx" > "$STATE"

IFS='|' read -r name border_a border_b inactive kitty_fg kitty_accent <<<"${PALETTES[$idx]}"
name=$(echo "$name" | xargs)
border_a=$(echo "$border_a" | xargs)
border_b=$(echo "$border_b" | xargs)
inactive=$(echo "$inactive" | xargs)
kitty_fg=$(echo "$kitty_fg" | xargs)
kitty_accent=$(echo "$kitty_accent" | xargs)

cat > "$OUT" <<EOF
# Generated by 8sync-palette-cycle.sh — DO NOT EDIT MANUALLY
# Palette: $name  (index $idx)

general {
    col.active_border = $border_a $border_b 45deg
    col.inactive_border = $inactive
}

# Hyprland reads col.* live via hyprctl, no reload needed.
EOF

# Live apply borders without a full reload (cheap).
if pgrep -x Hyprland >/dev/null 2>&1; then
    hyprctl --batch "\
        keyword general:col.active_border $border_a $border_b 45deg;\
        keyword general:col.inactive_border $inactive\
    " >/dev/null 2>&1 || true
fi

# Live-patch kitty if remote control is on. Falls back to silent.
if command -v kitty >/dev/null 2>&1 && [ -n "$KITTY_LISTEN_ON$KITTY_PID" ] || pgrep -x kitty >/dev/null; then
    # Only attempt if remote control enabled — error swallowed.
    kitty @ --to "unix:/tmp/8sync-kitty.sock" set-colors -a "color4=$kitty_accent" "color6=$kitty_accent" >/dev/null 2>&1 || \
    kitty @ set-colors -a "color4=$kitty_accent" "color6=$kitty_accent" >/dev/null 2>&1 || true
fi

# Notify.
if command -v notify-send >/dev/null 2>&1; then
    notify-send -t 2500 \
        -h "string:x-canonical-private-synchronous:8sync-palette" \
        "🎨 Palette: $name" \
        "border: $border_a → $border_b\naccent: $kitty_accent\n($((idx + 1))/${#PALETTES[@]})  Ctrl+Super+Shift+←/→ to cycle"
fi

echo "$name"
